version: '3.9'
services:
  orchestrator:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: law-final-orchestrator
    expose:
      - 5672
    ports:
      - '3000:3000'
    restart: always

  orchestrator2:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: orchestrator-copy-1
    expose:
      - 5672
    ports:
      - '3100:3000'
    restart: always

  nginx:
    image: nginx
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
