version: '3.9'
services:
  server:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: law-final-orchestrator
    ports:
      - '3010:3000'
    restart: always
