version: '3.9'
services:
  server:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: law-final-orchestrator
    ports:
      - '${D_PORT}:3000'
    restart: always

  mirror-server-1:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: law-final-orchestrator-mirror-1
    ports:
      - '${D_PORT_MIRROR_1}:3000'
    restart: always
