POST http://localhost:3000/order
Content-Type: application/json

{
    "name": "test",
    "description": "testos test"
}

###

POST http://localhost:3000/order/post-rabbitmq
Content-Type: application/json

{
    "name": "test",
    "description": "testos test"
}

###

GET http://localhost:3000/order/test

###
GET http://localhost:3000/orchestrator/order/publish-rabbit